language: ruby
rvm:
  - 2.0.0
  - 2.2.2
gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails4.gemfile
      rvm: 2.2.2
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.0.0
cache: bundler
